name: pm2-python3.8
on:
  push:
    branches: ['pm2-python3.8']
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASS }}
      - name: start build
        run: |
            cd base_docker/pm2-python3.8 && ./build.sh