name: ubuntu20.04
on:
  push:
    branches: ['ubuntu20.04']
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: start build
        run: |
            docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            cd base_docker/ubuntu20.04 && ./build.sh